name: trigger-resource

pool: selfHosted

trigger:
  branches:
    include:
      - main

stages:
- stage: stage_name
  jobs:
  - job: job_name
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          echo "triggered pipeline"

- stage: Production
  jobs:
  - job: job_name
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          echo "triggered pipeline"
